theme: jekyll-theme-midnight
exclude: [docker/src, docker/rollup.config.js, docker/tsconfig.json, docker/package.json, docker/package-lock.json, docker/build.sh, docker/build]
google_analytics: G-FZPMQC94M9
title: Omid Git Pages
description: My git pages including some light online tools and gists